# Generated by Django 6.0.6 on 2026-07-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendalibre', '0003_categoria_producto_imagen_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
